import { GameMode } from "./types/gameSettings";

const lakes = [
  {
    name: "Haapolahti",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_PASURI,
      GameMode.VAIN_PASURI_KAPPALEMAARA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    supportedNightModes: [
      GameMode.VAIN_MADE,
      GameMode.VAIN_MADE_KAPPALEMAARA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
    ],
    isNight: true,
  },
  {
    name: "Harjukankaan monttu",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_HAUKI,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.VAIN_SIIKA,
      GameMode.VAIN_SIIKA_KAPPALEMAARA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    supportedNightModes: [],
    isNight: false,
  },
  {
    name: "Haukilahti",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    supportedNightModes: [],
    isNight: true,
  },
  {
    name: "Hossalaislammet",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.KIRJO_JA_TAIMEN,
      GameMode.KIRJO_JA_TAIMEN_KAPPALEMAARA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.VAIN_SIIKA,
      GameMode.VAIN_SIIKA_KAPPALEMAARA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Iso-Ruuhijärvi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.KIRJO_JA_TAIMEN,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Iso-Söimi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.VAIN_SIIKA,
      GameMode.VAIN_SIIKA_KAPPALEMAARA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Jormuanlahti",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: true,
  },
  {
    name: "Kivijoki",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_HAUKI,
      GameMode.SUURIN_HAUKI,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Koivusaaren matalikko",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_KUHA,
      GameMode.SUURIN_KUHA,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: true,
  },
  {
    name: "Kolmisoppi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.KIRJO_JA_TAIMEN,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Korpipuro",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Kortejärvi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_HAUKI,
      GameMode.SUURIN_HAUKI,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Kuikansalmi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.KIRJO_JA_TAIMEN,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: true,
  },
  {
    name: "Kuopionlahti",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: true,
  },
  {
    name: "Lahnalammet",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_PASURI,
      GameMode.VAIN_PASURI_KAPPALEMAARA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_HAUKI,
      GameMode.SUURIN_HAUKI,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Lehmilampi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_PASURI,
      GameMode.VAIN_PASURI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Linlonlahti",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_KUHA,
      GameMode.SUURIN_KUHA,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: true,
  },
  {
    name: "Lokkiluoto",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_HAUKI,
      GameMode.SUURIN_HAUKI,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: true,
  },
  {
    name: "Meri",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Metsälampi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Muddusjärvi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Mustalampi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_HAUKI,
      GameMode.SUURIN_HAUKI,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Mäntylahti",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_PASURI,
      GameMode.VAIN_PASURI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_KUHA,
      GameMode.SUURIN_KUHA,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Niemisjärvet",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.KIRJO_JA_TAIMEN,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.VAIN_SIIKA,
      GameMode.VAIN_SIIKA_KAPPALEMAARA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Palusjärvi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_PASURI,
      GameMode.VAIN_PASURI_KAPPALEMAARA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_HAUKI,
      GameMode.SUURIN_HAUKI,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Peräjärvi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_HAUKI,
      GameMode.SUURIN_HAUKI,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: true,
  },
  {
    name: "Pieni Särkinen",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Pitkälampi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_HAUKI,
      GameMode.SUURIN_HAUKI,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Pohjalampi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Rautupuro",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.VAIN_SIIKA,
      GameMode.VAIN_SIIKA_KAPPALEMAARA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Ruippo",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_HAUKI,
      GameMode.SUURIN_HAUKI,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Räväjärvi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.VAIN_SIIKA,
      GameMode.VAIN_SIIKA_KAPPALEMAARA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Rönttäoja",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: true,
  },
  {
    name: "Saarijärvi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_HAUKI,
      GameMode.SUURIN_HAUKI,
      GameMode.VAIN_KUHA,
      GameMode.SUURIN_KUHA,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: true,
  },
  {
    name: "Savilahti",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_PASURI,
      GameMode.VAIN_PASURI_KAPPALEMAARA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: true,
  },
  {
    name: "Siika-Valkeinen",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.VAIN_SIIKA,
      GameMode.VAIN_SIIKA_KAPPALEMAARA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: true,
  },
  {
    name: "Siikakoski",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.VAIN_SIIKA,
      GameMode.VAIN_SIIKA_KAPPALEMAARA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Surrinlampi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Särkijärvi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.VAIN_PASURI,
      GameMode.VAIN_PASURI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Taivallampi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_HAUKI,
      GameMode.SUURIN_HAUKI,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Telkänlampi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Ullavanjärvi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_HAUKI,
      GameMode.SUURIN_HAUKI,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: true,
  },
  {
    name: "Venetjoen tekojärvi",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_HAUKI,
      GameMode.SUURIN_HAUKI,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: true,
  },
  {
    name: "Viitalampi",
    supportedGamemodes: [
       GameMode.NORMAALI,
       GameMode.KAPPALEMAARA,
       GameMode.KAIKKI_LAJIT,
       GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
       GameMode.SUURIN_KALA,
       GameMode.VAIN_AHVEN,
       GameMode.VAIN_AHVEN_KAPPALEMAARA,
       GameMode.VAIN_HAUKI,
       GameMode.SUURIN_HAUKI,
       GameMode.VAIN_SARKIKALAT,
       GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
       GameMode.KOLME_SUURINTA_KALAA,
       GameMode.VIISI_SUURINTA_KALAA,
       GameMode.RUUTUPILKKI,
       GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Vuolasniva",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.VAIN_SIIKA,
      GameMode.VAIN_SIIKA_KAPPALEMAARA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: false,
  },
  {
    name: "Vuontele",
    supportedGamemodes: [
      GameMode.NORMAALI,
      GameMode.KAPPALEMAARA,
      GameMode.KAIKKI_LAJIT,
      GameMode.KAIKKI_LAJIT_KAPPALEMAARA,
      GameMode.SUURIN_KALA,
      GameMode.ENITEN_LAJEJA,
      GameMode.VAIN_KIISKI,
      GameMode.VAIN_KIISKI_KAPPALEMAARA,
      GameMode.VAIN_AHVEN,
      GameMode.VAIN_AHVEN_KAPPALEMAARA,
      GameMode.VAIN_HAUKI,
      GameMode.SUURIN_HAUKI,
      GameMode.VAIN_SARKIKALAT,
      GameMode.VAIN_SARKIKALAT_KAPPALEMAARA,
      GameMode.SUURIN_SARKIKALA,
      GameMode.KOLME_SUURINTA_KALAA,
      GameMode.VIISI_SUURINTA_KALAA,
      GameMode.RUUTUPILKKI,
      GameMode.RUUTUPILKKI_KAPPALEMAARA,
    ],
    isNight: true,
  },
];

export default lakes;
